feature/backup-databases

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -1,1 +1,26 @@
 #!/usr/bin/env bash
+# A Bash script that generates a MySQL dump and creates a compressed archive out of it.
+
+# Check if the correct number of arguments is provided
+if [ "$#" -ne 1 ]; then
+    echo "Usage: $0 <mysql-root-password>"
+    exit 1
+fi
+
+MYSQL_ROOT_PASSWORD=$1
+BACKUP_DIR="$(pwd)"
+
+# Create a timestamp for the backup file
+TIMESTAMP=$(date +"%d-%m-%Y")
+
+# Create MySQL dump and check if mysqldump was successful
+if ! mysqldump -u root -p"${MYSQL_ROOT_PASSWORD}" --all-databases > backup.sql; then
+    echo "mysqldump failed"
+    exit 1
+fi
+
+# Create a compressed archive
+if ! tar -czvf "${BACKUP_DIR}/${TIMESTAMP}.tar.gz" backup.sql; then
+    echo "tar compression failed"
+    exit 1
+fi
